//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0f.30319.18444f
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using Random = UnityEngine.Random;

public static class Tools
{
	public static void PlaySoundFromGroup(this MonoBehaviour script, AudioClip[] group, float volume) {
		if (group.Length == 0) {
			return;
		}

		int which_shot = Random.Range (0, group.Length);
		script.gameObject.audio.PlayOneShot (group [which_shot], volume * PlayerPrefs.GetFloat ("sound_volume", 1.0f));
	}

	
	public static MonoBehaviour RecursiveHasScript(GameObject gobject, string script, int depth) {
		if (gobject.GetComponent (script)) {
			return  gobject.GetComponent (script);
		} else if (depth > 0 && gobject.transform.parent) {
			return RecursiveHasScript (gobject.transform.parent.gameObject, script, depth - 1);
		} else {
			return null;
		}
	}
	
	public static Quaternion RandomOrientation() {
		return Quaternion.EulerAngles(Random.Range(0,360),Random.Range(0,360),Random.Range(0,360));
	}
}

